baseControlType:
  baseVelocityControl: false
  basePositionControl: false
  baseJointVelocityControl: false
  baseJointCurrentControl: false
  baseJointToqueControl: true

armControlType:
  armJointPositionControl: true
  armJointVelocityControl: false
  armJointToqueControl: false
