hardware_control_loop:
  loop_hz: &loop_hz 30

arm_hardware_interface:
  joints: &arm_joints
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5
  gripper: &gripper_joints
    - gripper_finger_link_l
    - gripper_finger_link_r

youbot_arm/joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: *loop_hz

youbot_arm/gripper_pos_controller:
  type: position_controllers/JointGroupPositionController
  joints: *gripper_joints
  publish_rate: *loop_hz

youbot_arm/joints_eff_controller:
  type: effort_controllers/JointGroupEffortController
  joints: *arm_joints
  publish_rate: *loop_hz

youbot_arm/joints_vel_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints: *arm_joints
  publish_rate: *loop_hz

youbot_arm/joints_pos_controller:
  type: position_controllers/JointGroupPositionController
  joints: *arm_joints
  publish_rate: *loop_hz