hardware_control_loop:
  loop_hz: &loop_hz 125

base_hardware_interface:
  joints: &base_joints
    - wheel_joint_fl
    - wheel_joint_fr
    - wheel_joint_bl
    - wheel_joint_br

youbot_base/joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: *loop_hz

youbot_arm/joints_eff_controller:
  type: effort_controllers/JointGroupEffortController
  joints: *base_joints

youbot_arm/joints_vel_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints: *base_joints

youbot_arm/joints_pos_controller:
  type: position_controllers/JointGroupPositionController
  joints: *base_joints

youbot_base/mecanum_drive_controller:
  type: mecanum_drive_controller/MecanumDriveController
  front_left_wheel_joint: wheel_joint_fl
  back_left_wheel_joint: wheel_joint_bl
  front_right_wheel_joint: wheel_joint_fr
  back_right_wheel_joint: wheel_joint_br
  wheel_separation_x: 0.3
  wheel_separation_y: 0.47
  wheel_radius: 0.0475
